---
abstract: 'communicate with the i3 window manager'
author:
  - 'Michael Stapelberg, C<< <michael at i3wm.org> >>'
  - 'Michael Stapelberg'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-I3
no_index:
  directory:
    - inc
    - t
requires:
  AnyEvent: 0
  AnyEvent::Handle: 0
  AnyEvent::Socket: 0
  JSON::XS: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.12
